# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build and Publish Conventions
on:
  - push
  - pull_request


jobs:
  build_test:
    runs-on: ubuntu-latest
    name: "Build and test conventions"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Gradle"s
        uses: ./.github/actions/setup-gradle
      - name: "Build and test conventions"
        working-directory: "convention-plugins"
        run: ../gradlew build check
      - name: "Publish conventions"
        working-directory: "convention-plugins"
        run: ../gradlew publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
